name: Actionlint

on:
  pull_request:
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # We want to install Nix to provision shellcheck, so that actionlint doesn't install
      # its own shellcheck. This will also make sure that this pipeline runs using
      # the same shellcheck as the ones in Nix shells of developers.
      - name: Install Nix with good defaults
        uses: input-output-hk/install-nix-action@v20
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            substituters = https://cache.iog.io/ https://cache.nixos.org/
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      # Make the Nix environment available to next steps
      - uses: rrbutani/use-nix-shell-action@v1

      - name: Install actionlint
        run: |
          # Puts the "actionlint" binary in the working folder
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Run Actionlint
        run: |
          for file in $(git ls-files ".github/workflows/*.y*ml")
          do
            if grep -q "$file" ".github/workflows/actionlint-exceptions.txt"
            then
              echo "⚠️ $file is ignored from actionlint's verifications. Please consider fixing it."
            else
              echo "./actionlint $file"
              ./actionlint "$file"
            fi
          done
